### ISSUE TITLE
enhanceApp.js 解决中文路径问题出现 开发环境导航栏点击后直接跳转到生产环境页面

### ISSUE THREAD

**Issue by duktig666** [vuepress-reco/vuepress-theme-reco-1.x#402]
> 在你的仓库中的话可以 迭代一下
> 
> .vuepress/enhanceApp.js
> 
> ```js
> export default (ctx) => {
>   const routes = ctx.router.getRoutes()
>   
>   ctx.router.beforeEach((to, from, next) => {
>     // 解决decode后反复重定向的问题
>     const route = routes.find((v) => v.regex.test(to.path))
> 
>     // .html有重定向路由，无需特殊处理
>     if (/\.html$/.test(to.path)) {
>       return next()
>     }
> 
>     // 不特殊处理 非通配符的 没有重定向的路由
>     if (route && route.path !== '*' && !route.redirect) {
>       return next()
>     }
> 
>     // 解决中文标签/分类路由无法被正确加载的问题
>     if (decodeURIComponent(to.path) !== to.path) {
>       return next(
>         Object.assign({}, to, {
>           path: decodeURIComponent(to.path),
>           fullPath: decodeURIComponent(to.fullPath)
>         })
>       )
>     }
> 
>     next()
>   })
> 
>   // 临时解决，防止内部调用钩子再处理
>   ctx.router.beforeEach = () => {
>     return
>   }
> }
> 

经过测试已经成功解决了这个问题

_Originally posted by @duktig666 in https://github.com/vuepress-reco/vuepress-theme-reco-1.x/issues/395#issuecomment-1032088529_

**Comment by duktig666** [comment]
@ATQQ

**Comment by ATQQ** [comment]
不太清楚标题描述的问题，给个demo演示一下？

**Comment by duktig666** [comment]
## 问题

**开发环境点击中文路由**：
![开发环境点击中文路由](https://user-images.githubusercontent.com/53132746/157155196-786715ad-5a2d-48c7-95ff-60df17873366.png)
**点击中文路由跳转生产环境**：
![点击中文路由跳转生产环境](https://user-images.githubusercontent.com/53132746/157155253-e96f2fa9-204d-40d1-bde8-59d3f9e9db6c.png)
**导航栏配置**：
![导航栏配置](https://user-images.githubusercontent.com/53132746/157155334-78e62d6e-d843-4e4a-9eae-4d00172d2882.png)

## 信息
版本：1.6.10
开发环境：win10
生产环境：github pages
仓库地址：[https://github.com/duktig666/duktig666.github.io](https://github.com/duktig666/duktig666.github.io)





> 不太清楚标题描述的问题，给个demo演示一下？

**Comment by duktig666** [comment]
跳转到生产环境的链接 好像有重定向错误，具体如下：
https://www.duktig.cn/?error=redirect_uri_mismatch&error_description=The%20redirect_uri%20MUST%20match%20the%20registered%20callback%20URL%20for%20this%20application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=Vssue

**Comment by recoluan** [comment]
> 跳转到生产环境的链接 好像有重定向错误，具体如下： https://www.duktig.cn/?error=redirect_uri_mismatch&error_description=The%20redirect_uri%20MUST%20match%20the%20registered%20callback%20URL%20for%20this%20application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=Vssue

没有复现你所描述的问题呢
