### ISSUE TITLE
希望可以兼容fulltext-search全文搜索插件

### ISSUE THREAD

**Issue by RuanZhongNan** [vuepress-reco/vuepress-theme-reco-1.x#404]
#### What problem does this feature solve?
目前[reco-1.x](https://github.com/vuepress-reco/vuepress-theme-reco-1.x)主题没有提供更加合适的全文搜索工具，在自定义配置外部插件[vuepress-plugin-fulltext-search](https://github.com/leo-buneev/vuepress-plugin-fulltext-search)时，未能生效。希望可以兼容此插件，并实现全文搜索能力。

**Comment by recoluan** [comment]
1.x 不再做功能迭代。
