### ISSUE TITLE
Bug and Build with 1.6.13 and 1.6.10

### ISSUE THREAD

**Issue by joseluisgs** [vuepress-reco/vuepress-theme-reco-1.x#407]
- [X ] I confirm that this is an issue rather than a question.

## Bug report
Hi, I have my website with you theme, I use: npx @vuepress-reco/theme-cli init and instal 1x version in the past.
No problem, but today in another computer I install the web to check, and I have a problem with npm run build I think any package is updated and break anything. I install a clean vuepress roco web and I hace the same proble,

#### What is actually happening?
No problem when npm run dev, impossible to have a build version
✔ Client
  Compiled successfully in 13.19s

✔ Server
  Compiled successfully in 9.39s

wait Rendering static HTML...
[Vue warn]: Error in setup: "Error: must be called in setup"

found in

---> <Anonymous>
       <GlobalLayout>
         <Root>
error Error rendering /404.html: false
undefined
[Vue warn]: Error in setup: "Error: must be called in setup"

found in

---> <Tags>
       <GlobalLayout>
         <Root>
[Vue warn]: Error in setup: "Error: must be called in setup"

found in

---> <Anonymous>
       <GlobalLayout>
         <Root>
[Vue warn]: Error in setup: "Error: must be called in setup"

found in

---> <TimeLine>
       <GlobalLayout>
         <Root>
[Vue warn]: Error in setup: "Error: must be called in setup"

found in

---> <Tag>
       <GlobalLayout>
         <Root>
[Vue warn]: Error in setup: "Error: must be called in setup"

found in

---> <Tag>
       <GlobalLayout>
         <Root>
[Vue warn]: Error in setup: "Error: must be called in setup"

found in

---> <Tag>
       <GlobalLayout>
         <Root>
[Vue warn]: Error in setup: "Error: must be called in setup"

found in

---> <Tag>
       <GlobalLayout>
         <Root>
[Vue warn]: Error in setup: "Error: must be called in setup"

found in

---> <Category>
       <GlobalLayout>
         <Root>
[Vue warn]: Error in setup: "Error: must be called in setup"

found in

---> <Category>
       <GlobalLayout>
         <Root>
error Error rendering /tag/: false
undefined
error Error rendering /timeline/: false
undefined
error Error rendering /tag/tag1/: false
undefined
error Error rendering /tag/tag2/: false
undefined
error Error rendering /tag/tag3/: false
undefined
error Error rendering /tag/tag4/: false
undefined
error Error rendering /categories/category1/: false
undefined
error Error rendering /categories/category2/: false
undefined
[Vue warn]: Error in setup: "Error: must be called in setup"

found in

---> <Anonymous>
       <GlobalLayout>
         <Root>
[Vue warn]: Error in setup: "Error: must be called in setup"

found in

---> <Anonymous>
       <GlobalLayout>
         <Root>
[Vue warn]: Error in setup: "Error: must be called in setup"

found in

---> <Anonymous>
       <GlobalLayout>
         <Root>
[Vue warn]: Error in setup: "Error: must be called in setup"

found in

---> <Anonymous>
       <GlobalLayout>
         <Root>
[Vue warn]: Error in setup: "Error: must be called in setup"

found in

---> <Anonymous>
       <GlobalLayout>
         <Root>
[Vue warn]: Error in setup: "Error: must be called in setup"

found in

---> <Anonymous>
       <GlobalLayout>
         <Root>
[Vue warn]: Error in setup: "Error: must be called in setup"

found in

---> <Anonymous>
       <GlobalLayout>
         <Root>
[Vue warn]: Error in setup: "Error: must be called in setup"

found in

---> <Anonymous>
       <GlobalLayout>
         <Root>
[Vue warn]: Error in setup: "Error: must be called in setup"

found in

---> <Anonymous>
       <GlobalLayout>
         <Root>
[Vue warn]: Error in setup: "Error: must be called in setup"

found in

---> <Anonymous>
       <GlobalLayout>
         <Root>
error Error rendering /categories/: false
undefined
error Error rendering /: false
undefined
error Error rendering /blogs/category1/2018/121501.html: false
undefined
error Error rendering /blogs/category1/2019/092101.html: false
undefined
error Error rendering /blogs/category2/2016/121501.html: false
undefined
error Error rendering /blogs/other/guide.html: false
undefined
error Error rendering /docs/theme-reco/: false
undefined
error Error rendering /docs/theme-reco/api.html: false
undefined
error Error rendering /blogs/category2/2017/092101.html: false
undefined
error Error rendering /docs/theme-reco/plugin.html: false
undefined
error Error rendering /docs/theme-reco/theme.html: false
undefined
Error: must be called in setup
    at useInstance (node_modules/vuepress-theme-reco/helpers/composable.js:5:17)
    at setup (node_modules/vuepress-theme-reco/layouts/404.vue:14:32)
    at mergedSetupFn (node_modules/@vue/composition-api/dist/vue-composition-api.esm.js:1672:88)
    at invokeWithErrorHandling (/home/joseluisgs/Proyectos/web/node_modules/vue/dist/vue.runtime.common.dev.js:3895:30)
    at initSetup (/home/joseluisgs/Proyectos/web/node_modules/vue/dist/vue.runtime.common.dev.js:2313:29)
    at initState (/home/joseluisgs/Proyectos/web/node_modules/vue/dist/vue.runtime.common.dev.js:5117:5)
    at VueComponent.Vue._init (/home/joseluisgs/Proyectos/web/node_modules/vue/dist/vue.runtime.common.dev.js:5431:9)
    at new VueComponent (/home/joseluisgs/Proyectos/web/node_modules/vue/dist/vue.runtime.common.dev.js:5566:18)
    at createComponentInstanceForVnode (/home/joseluisgs/Proyectos/web/node_modules/vue-server-renderer/build.dev.js:1981:12)
    at renderComponentInner (/home/joseluisgs/Proyectos/web/node_modules/vue-server-renderer/build.dev.js:7184:45)
    at renderComponent (/home/joseluisgs/Proyectos/web/node_modules/vue-server-renderer/build.dev.js:7161:9)
    at resolve (/home/joseluisgs/Proyectos/web/node_modules/vue-server-renderer/build.dev.js:7210:17)

#### Other relevant information
I try with a new version of vue press and older version. I have the same problem 

- Your OS:  Linux and mac
- Node.js version: 16.5.1
- VuePress version:  1.8.2
- VuePress-theme-reco version: 1.6.10 and 1.6.13
- Which package manager did you use for the install(npm/cnpm/yarn)? npm

**Comment by 289373410** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by joseluisgs** [comment]
Please en english?

**Comment by joseluisgs** [comment]
I solve using my old package-lock
maybe it can help you
https://github.com/joseluisgs/joseluisgs/blob/master/web.back/packages/package-lock.json
https://github.com/joseluisgs/joseluisgs/blob/master/web.back/packages/package.json
Probably a dependece breaks the build mode
any idea?

**Comment by recoluan** [comment]
Hello friends, please try to upgrade to v1.6.14

**Comment by joseluisgs** [comment]
Hi, I will try it this monday :)

**Comment by joseluisgs** [comment]
Thank you very much! I' sorry, 
I haven't tried it yet.

But I guess everything will be great!
Thanks again

**Comment by dyj7** [comment]
i have the same question, after upgrade to v1.6.14 all resolved

**Comment by wuhou123** [comment]
已收到，谢谢
