### ISSUE TITLE
右侧二级侧边栏不能固定

### ISSUE THREAD

**Issue by AriseMarcher** [vuepress-reco/vuepress-theme-reco-1.x#408]
在线演示地址：https://arisemarcher.github.io/blog （点击gulp相关的一篇文章）
我的github地址：https://github.com/AriseMarcher/blog

**Comment by 289373410** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wuhou123** [comment]
已收到，谢谢

**Comment by AriseMarcher** [comment]
版本回退至1.6.13，暂时处理

**Comment by AriseMarcher** [comment]
版本回退至1.6.13，暂时处理
