### ISSUE TITLE
Vuepress配置sidebar分组的时候，首页左侧侧边栏无法关闭，readme.md已经配置过sidebar: false

### ISSUE THREAD

**Issue by wuranxu** [vuepress-reco/vuepress-theme-reco-1.x#412]
#### reco版本

   v1.6.14

#### vuepress

  v1.8.2

#### 🐛 现象

  按照vuepress文档设置`侧边栏`分组的时候，首页会出现`侧边栏`遮盖住博客首页，希望在`首页`的时候不展示`侧边栏`。

#### 📑 config.js配置

```javascript
    sidebar: [
      {
        title: '首页',
        path: '/'
      },
      {
        title: '目录1',   // 必要的
        collapsable: false, // 可选的, 默认值是 true,
        sidebarDepth: 2,    // 可选的, 默认值是 1
        children: [
          '/blogs/category1/2018/121501'
        ]
      },
      {
        title: '目录2',
        sidebarDepth: 2,
        collapsable: false,
        children: [
          '/blogs/category2/2017/092101'
        ],
      }
    ],
```

#### 📚 README.md

```markdown
---
home: true
sidebar: false
subSiderbar: false
heroText: vuepress-theme-reco
tagline: A simple and beautiful vuepress blog theme.
# heroImage: /hero.png
# heroImageStyle: {
#   maxWidth: '600px',
#   width: '100%',
#   display: block,
#   margin: '9rem auto 2rem',
#   background: '#fff',
#   borderRadius: '1rem',
# }
bgImageStyle: {
  height: '450px'
}
isShowTitleInHome: false
actionText: Guide
actionLink: /views/other/guide
features:
- title: Yesterday
  details: 开发一款看着开心、写着顺手的 vuepress 博客主题
- title: Today
  details: 希望帮助更多的人花更多的时间在内容创作上，而不是博客搭建上
- title: Tomorrow
  details: 希望更多的爱好者能够参与进来，帮助这个主题更好的成长
---
```

![image](https://user-images.githubusercontent.com/11266738/192770950-a4ac407f-25bb-4b43-80cc-c7280bbd6e28.png)

辛苦大佬帮忙看看了~

**Comment by recoluan** [comment]
请按照规范提交 issue，注明 vuepress 和 reco 主题的版本号

**Comment by recoluan** [comment]
Don't put home path into the sidebar config.

> #### reco版本
> v1.6.14
> 
> #### vuepress
> v1.8.2
> 
> #### 🐛 现象
> 按照vuepress文档设置`侧边栏`分组的时候，首页会出现`侧边栏`遮盖住博客首页，希望在`首页`的时候不展示`侧边栏`。
> 
> #### 📑 config.js配置
> ```js
>     sidebar: [
>       {
>         title: '首页',
>         path: '/'
>       },
>       {
>         title: '目录1',   // 必要的
>         collapsable: false, // 可选的, 默认值是 true,
>         sidebarDepth: 2,    // 可选的, 默认值是 1
>         children: [
>           '/blogs/category1/2018/121501'
>         ]
>       },
>       {
>         title: '目录2',
>         sidebarDepth: 2,
>         collapsable: false,
>         children: [
>           '/blogs/category2/2017/092101'
>         ],
>       }
>     ],
> ```
> 
> #### 📚 README.md
> ```gfm
> ---
> home: true
> sidebar: false
> subSiderbar: false
> heroText: vuepress-theme-reco
> tagline: A simple and beautiful vuepress blog theme.
> # heroImage: /hero.png
> # heroImageStyle: {
> #   maxWidth: '600px',
> #   width: '100%',
> #   display: block,
> #   margin: '9rem auto 2rem',
> #   background: '#fff',
> #   borderRadius: '1rem',
> # }
> bgImageStyle: {
>   height: '450px'
> }
> isShowTitleInHome: false
> actionText: Guide
> actionLink: /views/other/guide
> features:
> - title: Yesterday
>   details: 开发一款看着开心、写着顺手的 vuepress 博客主题
> - title: Today
>   details: 希望帮助更多的人花更多的时间在内容创作上，而不是博客搭建上
> - title: Tomorrow
>   details: 希望更多的爱好者能够参与进来，帮助这个主题更好的成长
> ---
> ```
> 
> ![image](https://user-images.githubusercontent.com/11266738/192770950-a4ac407f-25bb-4b43-80cc-c7280bbd6e28.png)
> 
> 辛苦大佬帮忙看看了~
