### ISSUE TITLE
The content is not displayed（白屏问题）

### ISSUE THREAD

**Issue by duktig666** [vuepress-reco/vuepress-theme-reco-1.x#413]
- [x] I confirm that this is an issue rather than a question.

## Bug report
exec `npm run dev`, When accessed in a browser, the entire page does not display the content.

#### What is actually happening?
白屏问题

![WechatIMG32084](https://user-images.githubusercontent.com/53132746/194695925-1cbcfa19-ae26-4b40-b697-ae76570bf59a.jpeg)

![WechatIMG32087](https://user-images.githubusercontent.com/53132746/194695894-88d209c8-10fe-4282-b0fe-da90c0f9acc9.jpeg)

#### Other relevant information

[BABEL] Note: The code generator has deoptimised the styling of xxx  the max of 500KB.

- Your OS: macos 12.6
- Node.js version: v14.19.3
- VuePress version: 1.8.2
- VuePress-theme-reco version: 1.6.10 or 1.6.15
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)? npm

**Comment by wencwcoder** [comment]
@duktig666 https://github.com/moefyit/vuepress-plugin-meting/issues/36，之前我也出现过这个问题，我直接停用 [vuepress-plugin-meting](https://github.com/moefyit/vuepress-plugin-meting)

**Comment by duktig666** [comment]
> 

我也是 之后就好了

**Comment by nikerck** [comment]
能把你的依赖包版本发给我吗？我遇到了相同问题，无法解决

**Comment by duktig666** [comment]
> vuepress-plugin-meting

[vuepress-plugin-meting](https://github.com/moefyit/vuepress-plugin-meting)
关掉这个插件就好了

**Comment by nikerck** [comment]
还有类似音乐播放插件推荐吗？
因为这个插件很好看，所以想保留。
我以为你解决这个插件问题，向你询问解决方法。
