### ISSUE TITLE
Clicking to expand the sidebar causes the page to refresh, and the sidebar does not expand

### ISSUE THREAD

**Issue by BigLiou** [vuepress-reco/vuepress-theme-reco-1.x#415]
- [x] I confirm that this is an issue rather than a question.

## Bug report
* The sidebar is set to collapsible, and when I click on the other collapsible sidebar, it doesn't expand and the page automatically refreshes, as shown in the GIF below
![GIF 2022-10-31 16-56-13](https://user-images.githubusercontent.com/52017859/198970967-45f63096-a148-49ef-bfec-b1d33d0a9565.gif)
* When I refresh the page and collapse the first expanded sidebar, I click on the other collapsed sidebar and the other collapsed sidebar will expand again, as shown in the GIF below
![GIF 2022-10-31 16-57-39](https://user-images.githubusercontent.com/52017859/198972271-791883d3-f472-4524-99d3-34ff6d9d474e.gif)

#### Other relevant information

- Your OS:  Windows 11 家庭中文版 22H2
- Node.js version:  v14.17.0
- VuePress version:  1.9.7
- VuePress-theme-reco version:  1.6.16
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)? npm

**Comment by wuhou123** [comment]
已收到，谢谢

**Comment by 289373410** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
